#!/bin/bash

BASEDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

exportPathFile="$BASEDIR/exportInstallDirPath"

aliasCmd1='alias exportInstallDirPath='
#aliasCmd2='"'
aliasCmd=$aliasCmd1'"'$exportPathFile'"'

echo $aliasCmd
echo $aliasCmd >> ~/.bashrc