#!/bin/bash

installDir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

#echo "Install Dir Is..."
#echo $installDir
#echo ""

cmd="$installDir"

exportcmd="export SCRAPINGBASEDIR='$cmd'"

echo $exportcmd

#echo "exportcmd is..."
#echo $exportcmd 
#echo ""


#echo $exportcmd >> ~/.bashrc
