#!/bin/bash

#Parameters


# PROCESS INPUT ARGUMENTS
# ====================================================
# number of expected input arguments (must update if more are added in development):
nxArg=1

# Check that expected number of input args were provided.
# If so, echo the inputs onto the command line such that they are present in the
# log output:

echo ""
echo "Cleaning Up Filenames in Input Directory.."
echo "Filth.. Scum .. Defilers of All that is Holy!!!"
echo "Keep yer filthy spaces and special characters out of yer file naming conventions!"
echo "Exorcizing the filename demons.."
echo ""

if [ "$#" -lt "$nxArg" ];
then
  echo "$0: Missing arguments"
  exit 1
elif [ "$#" -gt "$nxArg" ];
then
  echo "$0: Too many arguments: $@"
  exit 1
else
  echo "Input Arguments to clnFileNames:"
  echo "#########################################################################"
  echo "Number of arguments.: $#"
  echo "List of arguments...: $@"
  echo "Arg #1..............: $1 (Local Input Directory)"
  inDirLocal=$1
  #videoFile=$1
  #echo "Arg #2..............: $2 (Local Output Directory)"
  #dirLocal=$2
  #echo "Arg #3..............: $3"
  echo "#########################################################################"
  echo ""
fi


# Enter directory specified as inDirLocal
# Get list of files in directory
# Then iterate through file names looking for names with uncouth characters..
# replace these with suitable alternatives..
# ====================================================

demonCount=0 #initialize counter

cd $inDirLocal
fNamesBefore=$(find . -maxdepth 1 -type f)

for z in *" "*; do
    flist=(`ls *" "*`)
    len=${#flist[@]} #check how many files contained string..
    if [ "$len" -gt 1 ]
    then
    mv -- "$z" "${z// /_}"
    demonCount=$(($demonCount+1))
    fi
done



for z in *"("*; do
    flist=(`ls *"("*`)
    len=${#flist[@]} #check how many files contained string..
    if [ "$len" -gt 1 ]
    then
    mv -- "$z" "${z//'('/}"
    demonCount=$(($demonCount+1))
    fi
done


for z in *")"*; do
    flist=(`ls *")"*`)
    len=${#flist[@]} #check how many files contained string..
    if [ "$len" -gt 1 ]
    then
    mv -- "$z" "${z//')'/}"
    demonCount=$(($demonCount+1))
    fi
done

for z in *"__"*; do
    flist=(`ls *"__"*`)
    len=${#flist[@]} #check how many files contained string..
    if [ "$len" -gt 1 ]
    then
    mv -- "$z" "${z//'__'/_}"
    demonCount=$(($demonCount+1))
    fi
done

for z in *"_-_"*; do
    flist=(`ls *"_-_"*`)
    len=${#flist[@]} #check how many files contained string..
    if [ "$len" -gt 1 ]
    then
    mv -- "$z" "${z//'_-_'/_}"
    demonCount=$(($demonCount+1))
    fi
done

for z in *"__"*; do
    flist=(`ls *"__"*`)
    len=${#flist[@]} #check how many files contained string..
    if [ "$len" -gt 1 ]
    then
    mv -- "$z" "${z//'__'/_}"
    demonCount=$(($demonCount+1))
    fi
done

fNamesAfter=$(find . -maxdepth 1 -type f)
echo "Finished.."

if [ "$demonCount" -gt 0 ];
then
echo "Exorcized $demonCount demons from your filenames.. Let that be a lesson to ye!"
echo ""
elif [ "$demonCount" -lt 1 ];
then
echo "Your filenames were not possessed by any demons.. Onward, good steward of file naming!"
echo "Continue in the way of the light!"
echo ""
fi

echo "Filenames Before:"
echo "------------------------------------------------"
echo "$fNamesBefore"
echo "------------------------------------------------"
echo ""

echo "Filenames After:"
echo "------------------------------------------------"
echo "$fNamesAfter"
echo "------------------------------------------------"
echo ""
