#!/bin/bash

# function for opening the textyBeast gui

# save starting dir..
startDir=$(pwd)

# get the full path to the main package directory for this package on this machine
SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPTDIR
cd ..
BASEDIR=$(pwd)
cd $SCRIPTDIR

# save native path..
txtyBstLclPath=$BASEDIR/textyBeastLocal

#export ORIGINAL_PATH=$PATH

# activate gui env
source  $BASEDIR/envs/gui/env/bin/activate

# ensure txtyBstLclPath path is available
export PATH="$txtyBstLclPath:$PATH"

# run command to open gui:
echo "Starting the textyBeast GUI..."
echo ""
python3 $BASEDIR/envs/gui/env/lib/python3.9/site-packages/textyBeastGui_v12.py $BASEDIR
echo "Closing the textyBeast GUI..."
echo ""

#return to starting directory
cd $startDir
